name: check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test ${{ matrix.py }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v3
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Run test suite
        run: PYTHONPATH=. tox
